---
title: "NishantVelagapudi_JoshWilson_DanVolk"
author: "Nishant Velagapudi, Josh Wilson, Dan Volk"
date: "February 15, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read in Data

```{r cars}
library(car)
library(plyr)
library(ggplot2)
library(Hmisc)
library(stargazer)

#used for ggplot formatting
library(ggpubr)
library(gridExtra)

#change to your git location
setwd("~/Berkeley_MIDS_Homework/W271/Lab2/w271_lab2")

data <- read.csv("DeHartSimplified.csv", sep=",")
```

## Univariate Analysis

```{r}
summary(data)

par(mfrow=c(1,3))

#Variables of immediate interest: rosn = self-worth, nrel=negative relationship interactions, desired = desire to drink
hist(data$rosn)
hist(data$nrel)
hist(data$desired)

#We see that Id identifies a single respondant: each respondant has 7 responses (one for each day of the week)
count(data, id)

#We see a skewed response distribution by gender
count(data, gender)


```

## Bivariate Analysis
```{r}
#Split out three variables of interest by gender

biv_1 <- ggplot(data, aes(factor(gender), rosn)) + geom_boxplot(aes(fill=factor(gender))) +
         geom_jitter(width=0.1) + xlab("Gender")       + ggtitle("Self-worth")      +
         theme(plot.title=element_text(lineheight=1, face="bold"))

biv_2 <- ggplot(data, aes(factor(gender), negevent)) + geom_boxplot(aes(fill=factor(gender))) +
         geom_jitter(width=0.1) + xlab("negevent")       + ggtitle("Neg. Rel. Events")      +
         theme(plot.title=element_text(lineheight=1, face="bold"))

biv_3 <- ggplot(data, aes(factor(gender), desired)) + geom_boxplot(aes(fill=factor(gender))) +
         geom_jitter(width=0.1) + xlab("desired")       + ggtitle("Drinking Desire")      +
         theme(plot.title=element_text(lineheight=1, face="bold"))

ggarrange(biv_1, biv_2, biv_3, ncol=3, common.legend = TRUE, legend="bottom")
```

```{r, warning=FALSE}
scatterplotMatrix(data[c("nrel","desired","rosn"])
```
